In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn import preprocessing

import pickle


import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv(r'C:\Users\Acer\Downloads\train.csv')

In [3]:
df=pd.read_csv(r'C:\Users\Acer\Downloads\test.csv')

In [4]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,127,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2007,WD,Normal,128000
1,889,20,RL,95.0,15865,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2007,WD,Normal,268000
2,793,60,RL,92.0,9920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,269790
3,110,20,RL,105.0,11751,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,1,2010,COD,Normal,190000
4,422,20,RL,NaN,16635,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,215000

In [5]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,337,20,RL,86.0,14157,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
1,1018,120,RL,NaN,5814,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2009,COD,Abnorml
2,929,20,RL,NaN,11838,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
3,1148,70,RL,75.0,12000,Pave,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,7,2009,WD,Normal
4,1227,60,RL,86.0,14598,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal

In [6]:
data.shape

(1168, 81)

In [7]:
df.shape

(292, 80)

In [8]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1168.000000,1168.000000,954.00000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1161.000000,1168.000000,...,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000
mean,724.136130,56.767979,70.98847,10484.749144,6.104452,5.595890,1970.930651,1984.758562,102.310078,444.726027,...,96.206336,46.559932,23.015411,3.639555,15.051370,3.448630,47.315068,6.344178,2007.804795,181477.005993
std,416.159877,41.940650,24.82875,8957.442311,1.390153,1.124343,30.145255,20.785185,182.595606,462.664785,...,126.158988,66.381023,63.191089,29.088867,55.080816,44.896939,543.264432,2.686352,1.329738,79105.586863
min,1.000000,20.000000,21.00000,1300.000000,1.000000,1.000000,1875.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,360.500000,20.000000,60.00000,7621.500000,5.000000,5.000000,1954.000000,1966.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,130375.000000
50%,714.500000,50.000000,70.00000,9522.500000,6.000000,5.000000,1972.000000,1993.000000,0.000000,385.500000,...,0.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163995.000000
75%,1079.500000,70.000000,80.00000,11515.500000,7.000000,6.000000,2000.000000,2004.000000,160.000000,714.500000,...,171.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,215000.000000
max,1460.000000,190.000000,313.00000,164660.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [9]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,MiscVal,MoSold,YrSold
count,292.000000,292.000000,247.000000,292.000000,292.000000,292.000000,292.000000,292.000000,291.000000,292.000000,...,292.000000,292.000000,292.000000,292.000000,292.000000,292.0,0.0,292.000000,292.000000,292.000000
mean,755.955479,57.414384,66.425101,10645.143836,6.078767,5.493151,1972.616438,1985.294521,109.171821,439.294521,...,86.397260,47.061644,17.708904,2.489726,15.099315,0.0,NaN,28.184932,6.232877,2007.859589
std,442.565228,43.780649,21.726343,13330.669795,1.356147,1.063267,30.447016,20.105792,175.030021,429.559675,...,121.898836,65.865449,51.892906,30.247488,58.483473,0.0,NaN,224.036218,2.774556,1.322867
min,6.000000,20.000000,21.000000,1526.000000,3.000000,3.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,NaN,0.000000,1.000000,2006.000000
25%,377.750000,20.000000,53.500000,7200.000000,5.000000,5.000000,1954.000000,1968.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,NaN,0.000000,4.000000,2007.000000
50%,778.000000,50.000000,65.000000,9200.000000,6.000000,5.000000,1976.000000,1994.000000,0.000000,369.500000,...,0.000000,28.500000,0.000000,0.000000,0.000000,0.0,NaN,0.000000,6.000000,2008.000000
75%,1152.250000,70.000000,79.000000,11658.750000,7.000000,6.000000,2001.000000,2003.250000,180.000000,700.500000,...,149.250000,66.000000,0.000000,0.000000,0.000000,0.0,NaN,0.000000,8.000000,2009.000000
max,1456.000000,190.000000,150.000000,215245.000000,10.000000,9.000000,2009.000000,2010.000000,1031.000000,1767.000000,...,728.000000,418.000000,330.000000,407.000000,396.000000,0.0,NaN,3500.000000,12.000000,2010.000000

In [10]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      214
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [11]:
df.isnull().sum()

Id                0
MSSubClass        0
MSZoning          0
LotFrontage      45
LotArea           0
                 ..
MiscVal           0
MoSold            0
YrSold            0
SaleType          0
SaleCondition     0
Length: 80, dtype: int64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168 entries, 0 to 1167
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1168 non-null   int64
 1   MSSubClass     1168 non-null   int64
 2   MSZoning       1168 non-null   object
 3   LotFrontage    954 non-null    float64
 4   LotArea        1168 non-null   int64
 5   Street         1168 non-null   object
 6   Alley          77 non-null     object
 7   LotShape       1168 non-null   object
 8   LandContour    1168 non-null   object
 9   Utilities      1168 non-null   object
 10  LotConfig      1168 non-null   object
 11  LandSlope      1168 non-null   object
 12  Neighborhood   1168 non-null   object
 13  Condition1     1168 non-null   object
 14  Condition2     1168 non-null   object
 15  BldgType       1168 non-null   object
 16  HouseStyle     1168 non-null   object
 17  OverallQual    1168 non-null   int64
 18  OverallCond    1168 non-null   int64
 19  YearBuilt      1168 non-null   int64
 20  YearRemodAdd   1168 non-null   int64
 21  RoofStyle      1168 non-null   object
 22  RoofMatl       1168 non-null   object
 23  Exterior1st    1168 non-null   object
 24  Exterior2nd    1168 non-null   object
 25  MasVnrType     1161 non-null   object
 26  MasVnrArea     1161 non-null   float64
 27  ExterQual      1168 non-null   object
 28  ExterCond      1168 non-null   object
 29  Foundation     1168 non-null   object
 30  BsmtQual       1138 non-null   object
 31  BsmtCond       1138 non-null   object
 32  BsmtExposure   1137 non-null   object
 33  BsmtFinType1   1138 non-null   object
 34  BsmtFinSF1     1168 non-null   int64
 35  BsmtFinType2   1137 non-null   object
 36  BsmtFinSF2     1168 non-null   int64
 37  BsmtUnfSF      1168 non-null   int64
 38  TotalBsmtSF    1168 non-null   int64
 39  Heating        1168 non-null   object
 40  HeatingQC      1168 non-null   object
 41  CentralAir     1168 non-null   object
 42  Electrical     1168 non-null   object
 43  1stFlrSF       1168 non-null   int64
 44  2ndFlrSF       1168 non-null   int64
 45  LowQualFinSF   1168 non-null   int64
 46  GrLivArea      1168 non-null   int64
 47  BsmtFullBath   1168 non-null   int64
 48  BsmtHalfBath   1168 non-null   int64
 49  FullBath       1168 non-null   int64
 50  HalfBath       1168 non-null   int64
 51  BedroomAbvGr   1168 non-null   int64
 52  KitchenAbvGr   1168 non-null   int64
 53  KitchenQual    1168 non-null   object
 54  TotRmsAbvGrd   1168 non-null   int64
 55  Functional     1168 non-null   object
 56  Fireplaces     1168 non-null   int64
 57  FireplaceQu    617 non-null    object
 58  GarageType     1104 non-null   object
 59  GarageYrBlt    1104 non-null   float64
 60  GarageFinish   1104 non-null   object
 61  GarageCars     1168 non-null   int64
 62  GarageArea     1168 non-null   int64
 63  GarageQual     1104 non-null   object
 64  GarageCond     1104 non-null   object
 65  PavedDrive     1168 non-null   object
 66  WoodDeckSF     1168 non-null   int64
 67  OpenPorchSF    1168 non-null   int64
 68  EnclosedPorch  1168 non-null   int64
 69  3SsnPorch      1168 non-null   int64
 70  ScreenPorch    1168 non-null   int64
 71  PoolArea       1168 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          237 non-null    object
 74  MiscFeature    44 non-null     object
 75  MiscVal        1168 non-null   int64
 76  MoSold         1168 non-null   int64
 77  YrSold         1168 non-null   int64
 78  SaleType       1168 non-null   object
 79  SaleCondition  1168 non-null   object
 80  SalePrice      1168 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 739.2+ KB

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             292 non-null    int64
 1   MSSubClass     292 non-null    int64
 2   MSZoning       292 non-null    object
 3   LotFrontage    247 non-null    float64
 4   LotArea        292 non-null    int64
 5   Street         292 non-null    object
 6   Alley          14 non-null     object
 7   LotShape       292 non-null    object
 8   LandContour    292 non-null    object
 9   Utilities      292 non-null    object
 10  LotConfig      292 non-null    object
 11  LandSlope      292 non-null    object
 12  Neighborhood   292 non-null    object
 13  Condition1     292 non-null    object
 14  Condition2     292 non-null    object
 15  BldgType       292 non-null    object
 16  HouseStyle     292 non-null    object
 17  OverallQual    292 non-null    int64
 18  OverallCond    292 non-null    int64
 19  YearBuilt      292 non-null    int64
 20  YearRemodAdd   292 non-null    int64
 21  RoofStyle      292 non-null    object
 22  RoofMatl       292 non-null    object
 23  Exterior1st    292 non-null    object
 24  Exterior2nd    292 non-null    object
 25  MasVnrType     291 non-null    object
 26  MasVnrArea     291 non-null    float64
 27  ExterQual      292 non-null    object
 28  ExterCond      292 non-null    object
 29  Foundation     292 non-null    object
 30  BsmtQual       285 non-null    object
 31  BsmtCond       285 non-null    object
 32  BsmtExposure   285 non-null    object
 33  BsmtFinType1   285 non-null    object
 34  BsmtFinSF1     292 non-null    int64
 35  BsmtFinType2   285 non-null    object
 36  BsmtFinSF2     292 non-null    int64
 37  BsmtUnfSF      292 non-null    int64
 38  TotalBsmtSF    292 non-null    int64
 39  Heating        292 non-null    object
 40  HeatingQC      292 non-null    object
 41  CentralAir     292 non-null    object
 42  Electrical     291 non-null    object
 43  1stFlrSF       292 non-null    int64
 44  2ndFlrSF       292 non-null    int64
 45  LowQualFinSF   292 non-null    int64
 46  GrLivArea      292 non-null    int64
 47  BsmtFullBath   292 non-null    int64
 48  BsmtHalfBath   292 non-null    int64
 49  FullBath       292 non-null    int64
 50  HalfBath       292 non-null    int64
 51  BedroomAbvGr   292 non-null    int64
 52  KitchenAbvGr   292 non-null    int64
 53  KitchenQual    292 non-null    object
 54  TotRmsAbvGrd   292 non-null    int64
 55  Functional     292 non-null    object
 56  Fireplaces     292 non-null    int64
 57  FireplaceQu    153 non-null    object
 58  GarageType     275 non-null    object
 59  GarageYrBlt    275 non-null    float64
 60  GarageFinish   275 non-null    object
 61  GarageCars     292 non-null    int64
 62  GarageArea     292 non-null    int64
 63  GarageQual     275 non-null    object
 64  GarageCond     275 non-null    object
 65  PavedDrive     292 non-null    object
 66  WoodDeckSF     292 non-null    int64
 67  OpenPorchSF    292 non-null    int64
 68  EnclosedPorch  292 non-null    int64
 69  3SsnPorch      292 non-null    int64
 70  ScreenPorch    292 non-null    int64
 71  PoolArea       292 non-null    int64
 72  PoolQC         0 non-null      float64
 73  Fence          44 non-null     object
 74  MiscFeature    10 non-null     object
 75  MiscVal        292 non-null    int64
 76  MoSold         292 non-null    int64
 77  YrSold         292 non-null    int64
 78  SaleType       292 non-null    object
 79  SaleCondition  292 non-null    object
dtypes: float64(4), int64(34), object(42)
memory usage: 182.6+ KB

In [14]:
data=data.drop(columns=['Id','Alley','FireplaceQu','PoolQC','Fence', 'MiscFeature','MasVnrType'], axis=1, inplace=True)

In [15]:
df=df.drop(columns=['Id','Alley','FireplaceQu','PoolQC','Fence','MiscFeature','MasVnrType'], axis=1, inplace=True)

In [20]:
data['LotFrontage']=data['LotFrontage'].fillna(data['LotFrontage'].mode()[0])
data['MasVnrArea'].fillna(0, inplace=True)
data['BsmtQual'].fillna(method = 'bfill', inplace=True)
data['BsmtCond'].fillna(method = 'bfill', inplace=True)
data['BsmtExposure'].fillna('No', inplace=True)
data['BsmtFinType1'].fillna(method = 'bfill', inplace=True)
data['BsmtFinType2'].fillna(method = 'bfill', inplace=True)
data['Electrical'].fillna(method = 'bfill', inplace=True)
data['GarageType'].fillna(method = 'bfill', inplace=True)
data['GarageYrBlt'].fillna(method = 'bfill', inplace=True)
data['GarageFinish'].fillna(method = 'bfill', inplace=True)
data['GarageQual'].fillna(method = 'bfill', inplace=True)
data['GarageCond'].fillna(method = 'bfill', inplace=True)

TypeError: 'NoneType' object is not subscriptable

In [21]:
df['LotFrontage'].fillna(method = 'bfill', inplace=True)
df['MasVnrArea'].fillna(0, inplace=True)
df['BsmtQual'].fillna(method = 'bfill', inplace=True)
df['BsmtCond'].fillna(method = 'bfill', inplace=True)
df['BsmtExposure'].fillna('No', inplace=True)
df['BsmtFinType1'].fillna(method = 'bfill', inplace=True)
df['BsmtFinType2'].fillna(method = 'bfill', inplace=True)
df['Electrical'].fillna(method = 'bfill', inplace=True)
df['Electrical'].fillna(method = 'bfill', inplace=True)
df['BsmtFinSF1'].fillna(method = 'bfill', inplace=True)
df['BsmtFinSF2'].fillna(method = 'bfill', inplace=True)
df['BsmtUnfSF'].fillna(method = 'bfill', inplace=True)
df['TotalBsmtSF'].fillna(method = 'bfill', inplace=True)
df['BsmtFullBath'].fillna(method = 'bfill', inplace=True)
df['BsmtHalfBath'].fillna(method = 'bfill', inplace=True)
df['GarageYrBlt'].fillna(method = 'bfill', inplace=True)
df['GarageCars'].fillna(method = 'bfill', inplace=True)
df['GarageArea'].fillna(method = 'bfill', inplace=True)

TypeError: 'NoneType' object is not subscriptable

In [23]:
label_encoder = preprocessing.LabelEncoder()

data['MSZoning'] = label_encoder.fit_transform(data['MSZoning'])
data['Street'] = label_encoder.fit_transform(data['Street'])
data['LotShape'] = label_encoder.fit_transform(data['LotShape'])
data['LandContour'] = label_encoder.fit_transform(data['LandContour'])
data['Utilities'] = label_encoder.fit_transform(data['Utilities'])
data['LotConfig'] = label_encoder.fit_transform(data['LotConfig'])
data['LandSlope'] = label_encoder.fit_transform(data['LandSlope'])
data['Neighborhood'] = label_encoder.fit_transform(data['Neighborhood'])
data['Condition1'] = label_encoder.fit_transform(data['Condition1'])
data['Condition2'] = label_encoder.fit_transform(data['Condition2'])
data['BldgType'] = label_encoder.fit_transform(data['BldgType'])
data['HouseStyle'] = label_encoder.fit_transform(data['HouseStyle'])
data['RoofStyle'] = label_encoder.fit_transform(data['RoofStyle'])
data['RoofMatl'] = label_encoder.fit_transform(data['RoofMatl'])
data['Exterior1st'] = label_encoder.fit_transform(data['Exterior1st'])
data['Exterior2nd'] = label_encoder.fit_transform(data['Exterior2nd'])
data['ExterQual'] = label_encoder.fit_transform(data['ExterQual'])
data['ExterCond'] = label_encoder.fit_transform(data['ExterCond'])
data['Foundation'] = label_encoder.fit_transform(data['Foundation'])
data['BsmtQual'] = label_encoder.fit_transform(data['BsmtQual'])
data['BsmtCond'] = label_encoder.fit_transform(data['BsmtCond'])
data['BsmtExposure'] = label_encoder.fit_transform(data['BsmtExposure'])
data['BsmtFinType1'] = label_encoder.fit_transform(data['BsmtFinType1'])
data['BsmtFinType2'] = label_encoder.fit_transform(data['BsmtFinType2'])
data['Heating'] = label_encoder.fit_transform(data['Heating'])
data['HeatingQC'] = label_encoder.fit_transform(data['HeatingQC'])
data['CentralAir'] = label_encoder.fit_transform(data['CentralAir'])
data['Electrical'] = label_encoder.fit_transform(data['Electrical'])
data['KitchenQual'] = label_encoder.fit_transform(data['KitchenQual'])
data['Functional'] = label_encoder.fit_transform(data['Functional'])
data['GarageType'] = label_encoder.fit_transform(data['GarageType'])
data['GarageFinish'] = label_encoder.fit_transform(data['GarageFinish'])
data['GarageQual'] = label_encoder.fit_transform(data['GarageQual'])
data['GarageCond'] = label_encoder.fit_transform(data['GarageCond'])
data['PavedDrive'] = label_encoder.fit_transform(data['PavedDrive'])
data['SaleType'] = label_encoder.fit_transform(data['SaleType'])
data ['SaleCondition'] = label_encoder.fit_transform(data['SaleCondition'])

TypeError: 'NoneType' object is not subscriptable

In [24]:
df['MSZoning'] = label_encoder.fit_transform(df['MSZoning'])
df['Street'] = label_encoder.fit_transform(df['Street'])
df['LotShape'] = label_encoder.fit_transform(df['LotShape'])
df['LandContour'] = label_encoder.fit_transform(df['LandContour'])
df['Utilities'] = label_encoder.fit_transform(df['Utilities'])
df['LotConfig'] = label_encoder.fit_transform(df['LotConfig'])
df['LandSlope'] = label_encoder.fit_transform(df['LandSlope'])
df['Neighborhood'] = label_encoder.fit_transform(df['Neighborhood'])
df['Condition1'] = label_encoder.fit_transform(df['Condition1'])
df['Condition2'] = label_encoder.fit_transform(df['Condition2'])
df['BldgType'] = label_encoder.fit_transform(df['BldgType'])
df['HouseStyle'] = label_encoder.fit_transform(df['HouseStyle'])
df['RoofStyle'] = label_encoder.fit_transform(df['RoofStyle'])
df['RoofMatl'] = label_encoder.fit_transform(df['RoofMatl'])
df['Exterior1st'] = label_encoder.fit_transform(df['Exterior1st'])
df['Exterior2nd'] = label_encoder.fit_transform(df['Exterior2nd'])
df['ExterQual'] = label_encoder.fit_transform(df['ExterQual'])
df['ExterCond'] = label_encoder.fit_transform(df['ExterCond'])
df['Foundation'] = label_encoder.fit_transform(df['Foundation'])
df['BsmtQual'] = label_encoder.fit_transform(df['BsmtQual'])
df['BsmtCond'] = label_encoder.fit_transform(df['BsmtCond'])
df['BsmtExposure'] = label_encoder.fit_transform(df['BsmtExposure'])
df['BsmtFinType1'] = label_encoder.fit_transform(df['BsmtFinType1'])
df['BsmtFinType2'] = label_encoder.fit_transform(df['BsmtFinType2'])
df['Heating'] = label_encoder.fit_transform(df['Heating'])
df['HeatingQC'] = label_encoder.fit_transform(df['HeatingQC'])
df['CentralAir'] = label_encoder.fit_transform(df['CentralAir'])
df['Electrical'] = label_encoder.fit_transform(df['Electrical'])
df['KitchenQual'] = label_encoder.fit_transform(df['KitchenQual'])
df['Functional'] = label_encoder.fit_transform(df['Functional'])
df['GarageType'] = label_encoder.fit_transform(df['GarageType'])
df['GarageFinish'] = label_encoder.fit_transform(df['GarageFinish'])
df['GarageQual'] = label_encoder.fit_transform(df['GarageQual'])
df['GarageCond'] = label_encoder.fit_transform(df['GarageCond'])
df['PavedDrive'] = label_encoder.fit_transform(df['PavedDrive'])
df['SaleType'] = label_encoder.fit_transform(df['SaleType'])
df['SaleCondition'] = label_encoder.fit_transform(df['SaleCondition'])

TypeError: 'NoneType' object is not subscriptable

In [26]:
X = data.drop('SalePrice', axis=1)
y = data['SalePrice']

AttributeError: 'NoneType' object has no attribute 'drop'

In [27]:
plt.figure(figsize=(22,18))
ax = sns.heatmap(X.corr(), annot=True)
plt.show()

NameError: name 'X' is not defined

In [28]:
def correlation(dataset, threshold):
    col_corr = set() 
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold: 
                colname = corr_matrix.columns[i] 
                col_corr.add(colname)
    return col_corr

In [29]:
corr_features = correlation(X, 0.64)
len(set(corr_features))

NameError: name 'X' is not defined

In [30]:
X_corr = X.drop(corr_features,axis=1)
X_corr

NameError: name 'X' is not defined

In [32]:
df1 = df.drop(corr_features, axis=1)

AttributeError: 'NoneType' object has no attribute 'drop'

In [33]:
x_train, x_test,y_train,y_test = train_test_split(X_corr,y,test_size =0.3)

NameError: name 'X_corr' is not defined

In [34]:
clf = LinearRegression()

clf.fit(x_train,y_train)

NameError: name 'x_train' is not defined

In [36]:
pred = clf.predict(df1)
pred

NameError: name 'df1' is not defined

In [37]:
clf.score(x_test,y_test)

NameError: name 'x_test' is not defined